USE [INJIBOA]
GO
/****** Object:  StoredProcedure [dbo].[GENERAR_PRE_ANALISIS_FINAN]    Script Date: 01/07/2024 11:25:47 a.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [dbo].[GENERAR_PRE_ANALISIS_FINAN]
	@ID_ZAFRA_INI INT,
	@ID_ZAFRA_FIN INT,
	@CODIPROVEEDOR VARCHAR(50),
	@CONTRATOS VARCHAR(8000),
	@UID_REF VARCHAR(3000),
	@FECHA DATETIME,
	@USUARIO_CREA VARCHAR(100),
	@MONTO_SOLICITADO NUMERIC(20,2),
	@MONTO_SOLICITADO2 NUMERIC(20,2),
	@TIPO_MONTO_SOLICITADO VARCHAR(50), -- 'OIP', 'ANTICIPO',
	@UID_DOCUMENTO VARCHAR(300)
AS

BEGIN
	--DECLARE 
	--	@ID_ZAFRA_INI INT,
	--	@ID_ZAFRA_FIN INT,
	--	@CODIPROVEEDOR VARCHAR(50),
	--	@CONTRATOS VARCHAR(3000),
	--	@UID_REF VARCHAR(50),
	--	@FECHA DATETIME,
	--	@ID_DETA INT,
	--	@MONTO NUMERIC(20,4),		
	--	@USUARIO_CREA VARCHAR(100),
	--	@MONTO_SOLICITADO NUMERIC(20,2),
	--	@MONTO_SOLICITADO2 NUMERIC(20,2),
	--	@TIPO_MONTO_SOLICITADO VARCHAR(50),
	--	@UID_DOCUMENTO VARCHAR(50),
	--	@UID VARCHAR(300)
	--SET @ID_ZAFRA_INI = 10
	--SET @ID_ZAFRA_FIN = 15
	--SET @CODIPROVEEDOR = '0140150000'
	--SET @CONTRATOS = '2019/20200634;2020/20210608;'
	--SET @UID_REF = CAST(NEWID() AS VARCHAR(50))
	--SET @FECHA = GETDATE()
	--SET @USUARIO_CREA = 'admin'	
	--SET @MONTO_SOLICITADO = 0
	--SET @MONTO_SOLICITADO2 = 0
	--SET @TIPO_MONTO_SOLICITADO = ''
	--SET @UID_DOCUMENTO = ''
	--SET @UID = ''
	
	DECLARE @TABLA_CONTRATOS TBL_CONTRATOS_ANALIS,
			@UID_GUID AS UNIQUEIDENTIFIER

	set @FECHA = getdate()
	IF @UID_DOCUMENTO <> '' SET @UID_GUID = CAST(@UID_DOCUMENTO AS UNIQUEIDENTIFIER)

	DELETE FROM PRE_ANALISIS_ZAFRA 
		WHERE (SELECT COUNT(1) FROM PRE_ANALISIS_ENCA A WHERE A.ID_ENCA = PRE_ANALISIS_ZAFRA.ID_ENCA AND A.USUARIO_CREA = @USUARIO_CREA AND A.FECHA_CREA < @FECHA) > 0
	DELETE FROM PRE_ANALISIS_TC 
		WHERE (SELECT COUNT(1) FROM PRE_ANALISIS_ENCA A WHERE A.ID_ENCA = PRE_ANALISIS_TC.ID_ENCA AND A.USUARIO_CREA = @USUARIO_CREA AND A.FECHA_CREA < @FECHA) > 0
	DELETE FROM PRE_ANALISIS_DOCTO 
		WHERE (SELECT COUNT(1) FROM PRE_ANALISIS_ENCA A WHERE A.ID_ENCA = PRE_ANALISIS_DOCTO.ID_ENCA AND A.USUARIO_CREA = @USUARIO_CREA AND A.FECHA_CREA < @FECHA) > 0
	DELETE FROM PRE_ANALISIS_DETA WHERE USUARIO_CREA = @USUARIO_CREA AND FECHA_CREA < @FECHA
	DELETE FROM PRE_ANALISIS_ENCA WHERE USUARIO_CREA = @USUARIO_CREA AND FECHA_CREA < @FECHA

	
	DECLARE @POS INT,
			@CODICONTRATO VARCHAR(50),
			@NO_CONTRATOS VARCHAR(1000),									
			@ZONAS VARCHAR(1000),
			@TOTAL_MZ NUMERIC(20,4),
			@TOTAL_TC NUMERIC(20,4),
			@TOTAL_MZZ2 NUMERIC(20,4),
			@TOTAL_TCZ2 NUMERIC(20,4),
			@TARIFA_FLETE NUMERIC(20,4),
			@ID_ENCA INT,
			@CODIAGRON1 VARCHAR(8),
			@CODIAGRON2 VARCHAR(8),
			@CODIAGRON3 VARCHAR(8),

			@CUR_CODICONTRATO VARCHAR(1000),
			@CUR_NO_CONTRATO INT,
			@CUR_ZONA VARCHAR(100),			
			
			@@_DESEMBOLSOS_EFECTIVO NUMERIC(20,2),
			@@_SALDOS_INSOLUTOS NUMERIC(20,2),
			@@_OIP1 NUMERIC(20,2),
			@@_OIP2 NUMERIC(20,2),
			@@_OIP1_BANCO VARCHAR(200),
			@@_OIP2_BANCO VARCHAR(200),
			@@_OIP1_UID UNIQUEIDENTIFIER,
			@@_OIP2_UID UNIQUEIDENTIFIER,
			@@_SUMI_FERTILIZANTES NUMERIC(20,2),
			@@_SUMI_HERBICIDAS NUMERIC(20,2),
			@@_SUMI_INSECTICIDAS NUMERIC(20,2),
			@@_SUMI_INHIBIDORES NUMERIC(20,2),
			@@_ORDEN_TRAMITE NUMERIC(20,2),
			@@_OTRAS_CTAS NUMERIC(20,2),		
			@@_CANA_SEMILLA NUMERIC(20,2),
			@@_SERVICIO_MAQUI NUMERIC(20,2),
			@@_FOLIARES NUMERIC(20,2),
			@@_MADURANTES NUMERIC(20,2),
			@@_APLICACION_AEREA NUMERIC(20,2),
			@@_CREDITOS_LARGO_PLAZO NUMERIC(20,2),

			@@_DESEMBOLSOS_EFECTIVOZ2 NUMERIC(20,2),
			@@_SALDOS_INSOLUTOSZ2 NUMERIC(20,2),
			@@_OIP1Z2 NUMERIC(20,2),
			@@_OIP2Z2 NUMERIC(20,2),
			@@_OIP1_BANCOZ2 VARCHAR(200),
			@@_OIP2_BANCOZ2 VARCHAR(200),
			@@_OIP1_UIDZ2 UNIQUEIDENTIFIER,
			@@_OIP2_UIDZ2 UNIQUEIDENTIFIER,
			@@_SUMI_FERTILIZANTESZ2 NUMERIC(20,2),
			@@_SUMI_HERBICIDASZ2 NUMERIC(20,2),
			@@_SUMI_INSECTICIDASZ2 NUMERIC(20,2),
			@@_SUMI_INHIBIDORESZ2 NUMERIC(20,2),
			@@_ORDEN_TRAMITEZ2 NUMERIC(20,2),
			@@_OTRAS_CTASZ2 NUMERIC(20,2),		
			@@_CANA_SEMILLAZ2 NUMERIC(20,2),
			@@_SERVICIO_MAQUIZ2 NUMERIC(20,2),
			@@_FOLIARESZ2 NUMERIC(20,2),
			@@_MADURANTESZ2 NUMERIC(20,2),
			@@_APLICACION_AEREAZ2 NUMERIC(20,2),
			@@_CREDITOS_LARGO_PLAZOZ2 NUMERIC(20,2),

			@TOTAL_MZ_PROPIA NUMERIC(20,4),
			@TOTAL_MZ_PROPIAZ2 NUMERIC(20,4),
			@TOTAL_MZ_ARRENDADA NUMERIC(20,4),
			@TOTAL_MZ_ARRENDADAZ2 NUMERIC(20,4),
			@@ORDEN INT,
			@@MONTO1 NUMERIC(20,10),
			@@MONTO2 NUMERIC(20,10),
			@@MONTO3 NUMERIC(20,10),
			@@MONTO4 NUMERIC(20,10),
			@@MONTO5 NUMERIC(20,10),
			@@MONTO6 NUMERIC(20,10),
			
			@@PROVI_REAL_TC NUMERIC(20,10),
			@@PROVI_REAL_ROZA NUMERIC(20,10),
			@@PROVI_REAL_ALZA NUMERIC(20,10),
			@@PROVI_REAL_FLETE NUMERIC(20,10),
			@@PROVI_REAL_INGRESO NUMERIC(20,10),
			@@PROVI_REAL_EGRESO NUMERIC(20,10),
			@@CODIPROVEE VARCHAR(100),
			@@REND_HISTO NUMERIC(20,10),
			@@ID_ZAFRA_ACTUAL INT,
			@TASA_IVA NUMERIC(5,2) = 0.13

			
	SET @POS = 1		
	SET @CODICONTRATO = ''
	SET @@CODIPROVEE = LEFT(@CODIPROVEEDOR,6)

	SET @@ID_ZAFRA_ACTUAL = (SELECT ID_ZAFRA FROM ZAFRA WHERE ACTIVA = 1)
	SET @@REND_HISTO = (SELECT dbo.fDividir2Dec(sum(A.AZUCAR_CATORCENA_REAL),sum(B.NETOTONEL)) 
						FROM ENVIO E, ANALISIS A, BASCULA B
						WHERE E.CERRADO = 1 AND NOT A.AZUCAR_CATORCENA_REAL IS NULL
						AND E.ID_ENVIO = A.ID_ENVIO AND E.ID_ENVIO = B.ID_ENVIO
						AND E.ID_ZAFRA = @@ID_ZAFRA_ACTUAL
						AND (	SELECT COUNT(1) 
								FROM CONTRATO T, LOTES L 
								WHERE T.CODICONTRATO = L.CODICONTRATO AND L.ACCESLOTE = E.ACCESLOTE
								AND T.CODIPROVEEDOR = @CODIPROVEEDOR
							) > 0
						)
	IF @@REND_HISTO IS NULL 
		BEGIN
			SET @@REND_HISTO = (SELECT REND_MODFINAN FROM ZAFRA WHERE ID_ZAFRA = @@ID_ZAFRA_ACTUAL)
		END
				
	INSERT INTO @TABLA_CONTRATOS
	SELECT DISTINCT CZ.ID_ZAFRA, C.CODICONTRATO, C.NO_CONTRATO 
	FROM CONTRATO C, LOTES L, CONTRATO_ZAFRAS CZ
	WHERE C.CODICONTRATO = L.CODICONTRATO AND C.CODICONTRATO = CZ.CODICONTRATO
	AND C.CODIPROVEEDOR = @CODIPROVEEDOR AND CZ.ID_ZAFRA BETWEEN @ID_ZAFRA_INI AND @ID_ZAFRA_FIN

	-- Obteniendo números de contrato
	set @NO_CONTRATOS = ''
	set @TOTAL_MZ = 0
	set @TOTAL_TC = 0
	set @TOTAL_MZZ2 = 0
	set @TOTAL_TCZ2 = 0
	declare curc1 cursor for select distinct NO_CONTRATO from @TABLA_CONTRATOS order by NO_CONTRATO
	open curc1 fetch next from curc1 into @CUR_NO_CONTRATO

	while @@FETCH_STATUS = 0
		begin						
		set @NO_CONTRATOS = @NO_CONTRATOS + cast(@CUR_NO_CONTRATO as varchar) + ','										

		fetch next from curc1 into @CUR_NO_CONTRATO
		end
	close curc1
	deallocate curc1		
	set @NO_CONTRATOS = LEFT(@NO_CONTRATOS,LEN(@NO_CONTRATOS)-1)
		
	-- Obteniendo zonas
	set @ZONAS = ''
	declare curc2 cursor for select distinct L.ZONA from LOTES L where (select count(1) from @TABLA_CONTRATOS C where C.CODICONTRATO = L.CODICONTRATO) > 0 order by ZONA
	open curc2 fetch next from curc2 into @CUR_ZONA
	while @@FETCH_STATUS = 0				
		begin
				
		set @ZONAS = @ZONAS + @CUR_ZONA + ','				
		fetch next from curc2 into @CUR_ZONA
		end
	close curc2
	deallocate curc2
	set @ZONAS = LEFT(@ZONAS,LEN(@ZONAS)-1)


	CREATE TABLE #Z_COSECHA(
		ID_ZAFRA INT,
		EN_COSECHA BIT
	)
	CREATE TABLE #Z_RENDS(
		ID_ZAFRA INT,
		REND NUMERIC(20,2)
	)
	CREATE TABLE #DETA(
		ID_ZAFRA INT,
		ORDEN INT,
		VALOR NUMERIC(20,10) -- NUMERIC(20,4)
	)

	/* Asignando valores de rendimientos */
	INSERT INTO #Z_RENDS VALUES( @@ID_ZAFRA_ACTUAL, @@REND_HISTO)
	INSERT #Z_RENDS
	SELECT ID_ZAFRA, REND_MODFINAN FROM ZAFRA WHERE ID_ZAFRA >= @ID_ZAFRA_INI AND ID_ZAFRA <= @ID_ZAFRA_FIN
	AND ID_ZAFRA <> @@ID_ZAFRA_ACTUAL
	/* --------------------------------  */

	INSERT #Z_COSECHA
	SELECT DISTINCT LC.ID_ZAFRA, 1
	FROM LOTES L, LOTES_COSECHA LC 
	WHERE L.ACCESLOTE = LC.ACCESLOTE 
	AND LC.ID_ZAFRA BETWEEN @ID_ZAFRA_INI AND @ID_ZAFRA_FIN 
	AND (SELECT COUNT(1) FROM @TABLA_CONTRATOS C WHERE C.CODICONTRATO = L.CODICONTRATO ) > 0 

	INSERT #Z_COSECHA
	SELECT DISTINCT CZ.ID_ZAFRA, 0
	FROM LOTES L, CONTRATO_ZAFRAS CZ
	WHERE L.CODICONTRATO = CZ.CODICONTRATO
	AND CZ.ID_ZAFRA BETWEEN @ID_ZAFRA_INI AND @ID_ZAFRA_FIN 
	AND (SELECT COUNT(1) FROM #Z_COSECHA Z WHERE Z.ID_ZAFRA = CZ.ID_ZAFRA) = 0 
	AND (SELECT COUNT(1) FROM @TABLA_CONTRATOS C WHERE C.CODICONTRATO = L.CODICONTRATO ) > 0 

	-- TOTAL AREA CULTIVADA (EN COSECHA)
	INSERT #DETA
	SELECT LC.ID_ZAFRA, 1, SUM(LC.MZ_ENTREGAR) AS MZ_ENTREGAR
	FROM LOTES L, LOTES_COSECHA LC
	WHERE L.ACCESLOTE = LC.ACCESLOTE
	AND (SELECT COUNT(1) FROM #Z_COSECHA Z WHERE Z.ID_ZAFRA = LC.ID_ZAFRA AND Z.EN_COSECHA = 1) > 0
	AND (SELECT COUNT(1) FROM @TABLA_CONTRATOS C WHERE C.CODICONTRATO = L.CODICONTRATO ) > 0
	GROUP BY LC.ID_ZAFRA
	-- AREA CULTIVADA PROPIA (EN COSECHA)
	UNION ALL
	SELECT LC.ID_ZAFRA, 2, SUM(LC.MZ_ENTREGAR) AS MZ_ENTREGAR
	FROM LOTES L, LOTES_COSECHA LC
	WHERE L.ACCESLOTE = LC.ACCESLOTE
	AND L.TIPO_DERECHO = 1
	AND (SELECT COUNT(1) FROM #Z_COSECHA Z WHERE Z.ID_ZAFRA = LC.ID_ZAFRA AND Z.EN_COSECHA = 1) > 0
	AND (SELECT COUNT(1) FROM @TABLA_CONTRATOS C WHERE C.CODICONTRATO = L.CODICONTRATO ) > 0
	GROUP BY LC.ID_ZAFRA
	-- AREA CULTIVADA ARRENDADA (EN COSECHA)
	UNION ALL
	SELECT LC.ID_ZAFRA, 3, SUM(LC.MZ_ENTREGAR) AS MZ_ENTREGAR
	FROM LOTES L, LOTES_COSECHA LC
	WHERE L.ACCESLOTE = LC.ACCESLOTE
	AND L.TIPO_DERECHO <> 1
	AND (SELECT COUNT(1) FROM #Z_COSECHA Z WHERE Z.ID_ZAFRA = LC.ID_ZAFRA AND Z.EN_COSECHA = 1) > 0
	AND (SELECT COUNT(1) FROM @TABLA_CONTRATOS C WHERE C.CODICONTRATO = L.CODICONTRATO ) > 0
	GROUP BY LC.ID_ZAFRA
	-- TC/MZ (EN COSECHA)
	UNION ALL
	SELECT LC.ID_ZAFRA, 4, dbo.fDividir2Dec(SUM(LC.TONEL_ENTREGAR),SUM(LC.MZ_ENTREGAR)) AS MZ_ENTREGAR
	FROM LOTES L, LOTES_COSECHA LC
	WHERE L.ACCESLOTE = LC.ACCESLOTE
	AND (SELECT COUNT(1) FROM #Z_COSECHA Z WHERE Z.ID_ZAFRA = LC.ID_ZAFRA AND Z.EN_COSECHA = 1) > 0
	AND (SELECT COUNT(1) FROM @TABLA_CONTRATOS C WHERE C.CODICONTRATO = L.CODICONTRATO ) > 0
	GROUP BY LC.ID_ZAFRA
	-- TOTAL TC (EN COSECHA)
	UNION ALL
	SELECT LC.ID_ZAFRA, 5, SUM(LC.TONEL_ENTREGAR) AS MZ_ENTREGAR
	FROM LOTES L, LOTES_COSECHA LC
	WHERE L.ACCESLOTE = LC.ACCESLOTE
	AND (SELECT COUNT(1) FROM #Z_COSECHA Z WHERE Z.ID_ZAFRA = LC.ID_ZAFRA AND Z.EN_COSECHA = 1) > 0
	AND (SELECT COUNT(1) FROM @TABLA_CONTRATOS C WHERE C.CODICONTRATO = L.CODICONTRATO ) > 0
	GROUP BY LC.ID_ZAFRA
	-- LBS AZUCAR/TC (EN COSECHA)
	UNION ALL	
	SELECT C.ID_ZAFRA, 6, (SELECT R.REND FROM #Z_RENDS R WHERE R.ID_ZAFRA = C.ID_ZAFRA) FROM #Z_COSECHA C WHERE C.EN_COSECHA = 1
	-- TOTAL LBS AZUCAR (EN COSECHA)
	UNION ALL
	SELECT LC.ID_ZAFRA, 7, SUM(LC.TONEL_ENTREGAR)* R.REND AS MZ_ENTREGAR
	FROM LOTES L, LOTES_COSECHA LC, #Z_RENDS R
	WHERE L.ACCESLOTE = LC.ACCESLOTE
	AND LC.ID_ZAFRA = R.ID_ZAFRA
	AND (SELECT COUNT(1) FROM #Z_COSECHA Z WHERE Z.ID_ZAFRA = LC.ID_ZAFRA AND Z.EN_COSECHA = 1) > 0
	AND (SELECT COUNT(1) FROM @TABLA_CONTRATOS C WHERE C.CODICONTRATO = L.CODICONTRATO ) > 0
	GROUP BY LC.ID_ZAFRA, R.REND
	-- VIP	
	INSERT #DETA
	SELECT C.ID_ZAFRA, 8, (SELECT Z.PRECIO_LIBRA_AZUCAR FROM ZAFRA Z WHERE Z.ID_ZAFRA = C.ID_ZAFRA) FROM #Z_COSECHA C WHERE C.EN_COSECHA = 1	
	-- TOTAL AREA CULTIVADA (CONTRATO)
	INSERT #DETA
	SELECT CZ.ID_ZAFRA, 1, SUM(L.AREA) AS MZ_ENTREGAR
	FROM LOTES L, CONTRATO_ZAFRAS CZ
	WHERE L.CODICONTRATO = CZ.CODICONTRATO
	AND (SELECT COUNT(1) FROM #Z_COSECHA Z WHERE Z.ID_ZAFRA = CZ.ID_ZAFRA AND Z.EN_COSECHA = 0) > 0
	AND (SELECT COUNT(1) FROM @TABLA_CONTRATOS C WHERE C.CODICONTRATO = L.CODICONTRATO ) > 0
	GROUP BY CZ.ID_ZAFRA
	-- AREA CULTIVADA PROPIA (CONTRATO)
	UNION ALL
	SELECT CZ.ID_ZAFRA, 2, SUM(L.AREA) AS MZ_ENTREGAR
	FROM LOTES L, CONTRATO_ZAFRAS CZ
	WHERE L.CODICONTRATO = CZ.CODICONTRATO
	AND L.TIPO_DERECHO = 1
	AND (SELECT COUNT(1) FROM #Z_COSECHA Z WHERE Z.ID_ZAFRA = CZ.ID_ZAFRA AND Z.EN_COSECHA = 0) > 0
	AND (SELECT COUNT(1) FROM @TABLA_CONTRATOS C WHERE C.CODICONTRATO = L.CODICONTRATO ) > 0
	GROUP BY CZ.ID_ZAFRA
	-- AREA CULTIVADA ARRENDADA (CONTRATO)
	UNION ALL
	SELECT CZ.ID_ZAFRA, 2, SUM(L.AREA) AS MZ_ENTREGAR
	FROM LOTES L, CONTRATO_ZAFRAS CZ
	WHERE L.CODICONTRATO = CZ.CODICONTRATO
	AND L.TIPO_DERECHO <> 1
	AND (SELECT COUNT(1) FROM #Z_COSECHA Z WHERE Z.ID_ZAFRA = CZ.ID_ZAFRA AND Z.EN_COSECHA = 0) > 0
	AND (SELECT COUNT(1) FROM @TABLA_CONTRATOS C WHERE C.CODICONTRATO = L.CODICONTRATO ) > 0
	GROUP BY CZ.ID_ZAFRA
	-- TC/MZ (CONTRATO)
	UNION ALL
	SELECT CZ.ID_ZAFRA, 4, AVG(L.TONELADAS) AS MZ_ENTREGAR
	FROM LOTES L, CONTRATO_ZAFRAS CZ
	WHERE L.CODICONTRATO = CZ.CODICONTRATO
	AND (SELECT COUNT(1) FROM #Z_COSECHA Z WHERE Z.ID_ZAFRA = CZ.ID_ZAFRA AND Z.EN_COSECHA = 0) > 0
	AND (SELECT COUNT(1) FROM @TABLA_CONTRATOS C WHERE C.CODICONTRATO = L.CODICONTRATO ) > 0
	GROUP BY CZ.ID_ZAFRA
	-- TOTAL TC (CONTRATO)
	UNION ALL
	SELECT CZ.ID_ZAFRA, 5, SUM(L.TONEL_TC) AS MZ_ENTREGAR
	FROM LOTES L, CONTRATO_ZAFRAS CZ
	WHERE L.CODICONTRATO = CZ.CODICONTRATO
	AND (SELECT COUNT(1) FROM #Z_COSECHA Z WHERE Z.ID_ZAFRA = CZ.ID_ZAFRA AND Z.EN_COSECHA = 0) > 0
	AND (SELECT COUNT(1) FROM @TABLA_CONTRATOS C WHERE C.CODICONTRATO = L.CODICONTRATO ) > 0
	GROUP BY CZ.ID_ZAFRA
	-- LBS AZUCAR/TC (EN COSECHA)
	UNION ALL
	SELECT C.ID_ZAFRA, 6, (SELECT R.REND FROM #Z_RENDS R WHERE R.ID_ZAFRA = C.ID_ZAFRA) FROM #Z_COSECHA C WHERE C.EN_COSECHA = 0
	-- TOTAL LBS AZUCAR (EN COSECHA)
	UNION ALL
	SELECT CZ.ID_ZAFRA, 7, SUM(L.TONEL_TC)* R.REND AS MZ_ENTREGAR
	FROM LOTES L, CONTRATO_ZAFRAS CZ, #Z_RENDS R
	WHERE L.CODICONTRATO = CZ.CODICONTRATO
	AND CZ.ID_ZAFRA = R.ID_ZAFRA
	AND (SELECT COUNT(1) FROM #Z_COSECHA Z WHERE Z.ID_ZAFRA = CZ.ID_ZAFRA AND Z.EN_COSECHA = 0) > 0
	AND (SELECT COUNT(1) FROM @TABLA_CONTRATOS C WHERE C.CODICONTRATO = L.CODICONTRATO ) > 0
	GROUP BY CZ.ID_ZAFRA, R.REND
	-- VIP
	INSERT #DETA
	SELECT C.ID_ZAFRA, 8, (SELECT Z.PRECIO_LIBRA_AZUCAR FROM ZAFRA Z WHERE Z.ID_ZAFRA = C.ID_ZAFRA) FROM #Z_COSECHA C WHERE C.EN_COSECHA = 0
	-- =====================================================================================
	-- INGRESOS PROYECTADOS
	INSERT #DETA
	SELECT D.ID_ZAFRA, 9, ROUND(VALOR * (SELECT Z.PRECIO_LIBRA_AZUCAR FROM ZAFRA Z WHERE Z.ID_ZAFRA = D.ID_ZAFRA),2)
	FROM #DETA D
	WHERE D.ORDEN = 7
	
	-- =====================================================================================
	-- CAT (CORTE)
	INSERT #DETA
	SELECT D.ID_ZAFRA, 11, ROUND(VALOR * (SELECT Z.TARIFA_ROZA_MODFINAN + ROUND(Z.TARIFA_ROZA_MODFINAN * @TASA_IVA ,2) FROM ZAFRA Z WHERE Z.ID_ZAFRA = D.ID_ZAFRA),2)
	FROM #DETA D
	WHERE D.ORDEN = 5
	-- CAT (ALZA)
	INSERT #DETA
	SELECT D.ID_ZAFRA, 12, ROUND(VALOR * (SELECT Z.TARIFA_ALZA_MODFINAN + ROUND(Z.TARIFA_ALZA_MODFINAN * @TASA_IVA ,2) FROM ZAFRA Z WHERE Z.ID_ZAFRA = D.ID_ZAFRA),2)
	FROM #DETA D
	WHERE D.ORDEN = 5
	-- CAT (TRANSPORTE)
	INSERT #DETA
	SELECT D.ID_ZAFRA, 13, ROUND(VALOR * 
				(	SELECT CAST(ISNULL(AVG(LC.TARIFA_CORTA),0) AS NUMERIC(20,2)) + ROUND(CAST(ISNULL(AVG(LC.TARIFA_CORTA),0) AS NUMERIC(20,2)) * @TASA_IVA ,2) 
					FROM LOTES L, LOTES_COSECHA LC 
					WHERE NOT LC.TARIFA_CORTA IS NULL 
					AND L.ACCESLOTE = LC.ACCESLOTE 
					AND (SELECT COUNT(1) FROM @TABLA_CONTRATOS C WHERE L.CODICONTRATO = C.CODICONTRATO) > 0
				)
			,2)
	FROM #DETA D
	WHERE D.ORDEN = 5 AND (SELECT COUNT(1) FROM #Z_COSECHA C WHERE C.ID_ZAFRA = D.ID_ZAFRA AND C.EN_COSECHA = 1) > 0
	UNION ALL	
	SELECT D.ID_ZAFRA, 13, ROUND(VALOR * 
				(	
					SELECT AVG(TARIFA_AJUSTADA) + ROUND(AVG(TARIFA_AJUSTADA) * @TASA_IVA ,2)
					FROM (
						SELECT  (SELECT K.TARIFA_AJUSTADA FROM TARIFA_TRANS_X_KILO K WHERE N.KILOMETROS BETWEEN K.KILO_INI AND K.KILO_FIN)	AS TARIFA_AJUSTADA								    								
						FROM LOTES L, MAESTRO_LOTES ML, CANTON N
						WHERE L.ID_MAESTRO = ML.ID_MAESTRO		
						AND ML.CODI_DEPTO = N.CODI_DEPTO AND ML.CODI_MUNI = N.CODI_MUNI AND ML.CODI_CANTON = N.CODI_CANTON														
						AND (SELECT COUNT(1) FROM @TABLA_CONTRATOS C WHERE C.CODICONTRATO = L.CODICONTRATO) > 0 	
					) T															
				)
			,2)
	FROM #DETA D
	WHERE D.ORDEN = 5 AND (SELECT COUNT(1) FROM #Z_COSECHA C WHERE C.ID_ZAFRA = D.ID_ZAFRA AND C.EN_COSECHA = 0) > 0


	SET @TARIFA_FLETE = ISNULL(	(	SELECT AVG(TARIFA_AJUSTADA) + ROUND(AVG(TARIFA_AJUSTADA) * @TASA_IVA ,2)
									FROM (
										SELECT  (SELECT K.TARIFA_AJUSTADA FROM TARIFA_TRANS_X_KILO K WHERE N.KILOMETROS BETWEEN K.KILO_INI AND K.KILO_FIN)	AS TARIFA_AJUSTADA								    								
										FROM LOTES L, MAESTRO_LOTES ML, CANTON N
										WHERE L.ID_MAESTRO = ML.ID_MAESTRO		
										AND ML.CODI_DEPTO = N.CODI_DEPTO AND ML.CODI_MUNI = N.CODI_MUNI AND ML.CODI_CANTON = N.CODI_CANTON														
										AND (SELECT COUNT(1) FROM @TABLA_CONTRATOS C WHERE C.CODICONTRATO = L.CODICONTRATO) > 0 	
									) T	
								) ,4.70)


	-- CAT TOTAL
	INSERT #DETA
	SELECT D.ID_ZAFRA, 10, SUM(VALOR)
	FROM #DETA D
	WHERE D.ORDEN IN(11,12,13)
	GROUP BY D.ID_ZAFRA
	-- INGRESOS DESPUES DE CAT
	INSERT #DETA
	SELECT D.ID_ZAFRA, 15, VALOR - (SELECT X.VALOR FROM #DETA X WHERE X.ID_ZAFRA = D.ID_ZAFRA AND X.ORDEN = 10)
	FROM #DETA D
	WHERE D.ORDEN = 9	
	-- SALDOS INSOLUTOS
	INSERT #DETA
	SELECT @ID_ZAFRA_INI AS ID_ZAFRA, 17, SUM(C.SALDO + C.INTERES + C.IVA_INTERES)
	FROM CREDITO_ENCA C 
	WHERE C.CODIPROVEEDOR = @CODIPROVEEDOR AND C.ID_ZAFRA < @ID_ZAFRA_INI AND SALDO > 0		
		
	-- FINANCIAMIENTOS
	INSERT #DETA
	SELECT ID_ZAFRA, ORDEN, SUM(MONTO)
	FROM (
		select S.ID_ZAFRA, 
				CASE
					WHEN S.ID_CUENTA_FINAN = 7 THEN 18
					WHEN S.ID_CUENTA_FINAN = 26 THEN 19
					WHEN S.ID_CUENTA_FINAN = 28 THEN 20
					WHEN S.ID_CUENTA_FINAN = 11 THEN 21
					WHEN S.ID_CUENTA_FINAN = 17 THEN 22
					WHEN S.ID_CUENTA_FINAN = 3 THEN 23					
					WHEN S.ID_CUENTA_FINAN IN(13,19) AND (SELECT COUNT(1) FROM SOLIC_AGRICOLA_VUELO V WHERE V.ID_SOLICITUD = S.ID_SOLICITUD ) > 0 THEN 27
					WHEN S.ID_CUENTA_FINAN = 31 THEN 28
					WHEN S.ID_CUENTA_FINAN IN(15,22,21,32,33,47,48) THEN 29
					ELSE NULL
				END AS ORDEN,
				ISNULL((SELECT SUM(SP.PRECIO_TOTAL) FROM SOLIC_AGRICOLA_PRODUCTO SP WHERE SP.ID_SOLICITUD = S.ID_SOLICITUD),0) + 
						ROUND(ISNULL((SELECT SUM(SP.PRECIO_TOTAL) FROM SOLIC_AGRICOLA_PRODUCTO SP WHERE SP.ID_SOLICITUD = S.ID_SOLICITUD),0) * (SELECT TASA_IVA FROM PARAMETROS),2)	
						AS MONTO
		from SOLIC_AGRICOLA S 					
		WHERE S.ESTADO = 2 AND S.CONDI_COMPRA IN(1,3) 
		AND (SELECT COUNT(1) FROM CCF_ENCA CE WHERE CE.ID_SOLICITUD = S.ID_SOLICITUD) = 0 
		AND (SELECT COUNT(1) FROM CCF_DETA_SALBODE CS WHERE CS.ID_SOLICITUD = S.ID_SOLICITUD) = 0		 					
		AND S.CODIPROVEEDOR = @CODIPROVEEDOR
		AND S.ID_ZAFRA BETWEEN @ID_ZAFRA_INI AND @ID_ZAFRA_FIN
		UNION ALL
		select CF.ID_ZAFRA, 
				CASE
					WHEN CF.ID_CUENTA_FINAN = 7 THEN 18
					WHEN CF.ID_CUENTA_FINAN = 26 THEN 19
					WHEN CF.ID_CUENTA_FINAN = 28 THEN 20
					WHEN CF.ID_CUENTA_FINAN = 11 THEN 21
					WHEN CF.ID_CUENTA_FINAN = 17 THEN 22
					WHEN CF.ID_CUENTA_FINAN = 3 THEN 23
					WHEN CF.ID_CUENTA_FINAN IN(5,49,50,51) THEN 24
					WHEN CF.ID_CUENTA_FINAN = 6 THEN 25
					WHEN CF.ID_CUENTA_FINAN IN(13,19) THEN 27
					WHEN CF.ID_CUENTA_FINAN = 31 THEN 28
					WHEN CF.ID_CUENTA_FINAN IN(15,22,21,32,33,47,48) THEN 29
					ELSE NULL
				END AS ORDEN,
				SUM(CF.SALDO + CF.INTERES + CF.IVA_INTERES) AS MONTO
		from CREDITO_ENCA CF 
		WHERE CF.CODIPROVEEDOR = @CODIPROVEEDOR  
		AND CF.ID_ZAFRA BETWEEN @ID_ZAFRA_INI AND @ID_ZAFRA_FIN
		--AND CF.ES_SALDO_INSOLUTO = 0
		GROUP BY CF.ID_ZAFRA, CF.ID_CUENTA_FINAN
	) T
	WHERE NOT ORDEN IS NULL
	GROUP BY ID_ZAFRA, ORDEN	
	

	-- OIP
	INSERT #DETA	
	SELECT
			sa.ID_ZAFRA,
			31 AS ORDEN,
			SUM(E.SALDO) AS SALDO
	FROM SOLIC_OPI sa, BANCOS b, CREDITO_ENCA E 
	WHERE SA.UID_OPI_CONTRATO = E.UID_REFERENCIA and 
	sa.ID_ESTADO = 2 and 
	sa.CODIBANCO = b.CODIBANCO and 
	sa.ID_ZAFRA BETWEEN @ID_ZAFRA_INI AND @ID_ZAFRA_FIN and sa.CODIPROVEEDOR = @CODIPROVEEDOR
	GROUP BY sa.ID_ZAFRA
	
	
	-- ****** Encabezado			
	SET @ID_ENCA = (SELECT ISNULL(MAX(ID_ENCA),0) + 1 FROM PRE_ANALISIS_ENCA)

	insert into PRE_ANALISIS_ENCA 
	values( @ID_ENCA, @UID_REF, @ID_ZAFRA_INI, @FECHA, @CODIPROVEEDOR, 
	(SELECT RTRIM(ISNULL(NOMBRES,'')) + ' ' + RTRIM(ISNULL(APELLIDOS,'')) FROM PROVEEDOR WHERE CODIPROVEEDOR = @CODIPROVEEDOR),
	@NO_CONTRATOS, @ZONAS, 0, 0, 0, '', 0, @USUARIO_CREA, GETDATE(), @CODIAGRON1, @CODIAGRON2, @CODIAGRON3)

	-- ****** Documentos en trámite		
	exec GENERAR_PRE_ANALISIS_DOCTO @ID_ENCA, @ID_ZAFRA_INI, @ID_ZAFRA_FIN, @TABLA_CONTRATOS
	IF @UID_DOCUMENTO <> '' DELETE FROM PRE_ANALISIS_DOCTO WHERE UID_DOCUMENTO = @UID_GUID

	-- SOLICITUDES EN TRAMITE
	INSERT #DETA
	SELECT 
		ID_ZAFRA, 30 AS ORDEN, SUM(MONTO) AS MONTO
	FROM (
		SELECT 
			S.ID_ZAFRA, SUM(P.MONTO) AS MONTO
		FROM PRE_ANALISIS_DOCTO P, SOLIC_AGRICOLA S
		WHERE P.ID_ENCA = @ID_ENCA AND P.CATEGORIA = 'ORDEN DE INSUMO EN TRAMITE'
		AND S.UID_SOLIC_AGRICOLA = P.UID_DOCUMENTO
		GROUP BY S.ID_ZAFRA
		UNION ALL
		SELECT 
			S.ID_ZAFRA, SUM(P.MONTO) AS MONTO
		FROM PRE_ANALISIS_DOCTO P, SOLIC_OPI S
		WHERE P.ID_ENCA = @ID_ENCA AND P.CATEGORIA = 'ORDEN DE INSUMO EN TRAMITE'
		AND S.UID_OPI_CONTRATO = P.UID_DOCUMENTO
		GROUP BY S.ID_ZAFRA
		UNION ALL
		SELECT 
			S.ID_ZAFRA, SUM(P.MONTO) AS MONTO
		FROM PRE_ANALISIS_DOCTO P, SOLIC_ANTICIPO S
		WHERE P.ID_ENCA = @ID_ENCA AND P.CATEGORIA = 'ORDEN DE INSUMO EN TRAMITE'
		AND S.UID_ANTICIPO_CONTRATO = P.UID_DOCUMENTO
		AND (SELECT COUNT(1) FROM SOLIC_ANTICIPO_ZAFRA Z WHERE Z.ID_ANTICIPO = S.ID_ANTICIPO) = 0
		GROUP BY S.ID_ZAFRA
	) X
	GROUP BY ID_ZAFRA

	

	-- ****** Detalle		
	----set @@_DESEMBOLSOS_EFECTIVO = isnull(  (select sum(e.SALDO + e.INTERES + e.IVA_INTERES) from CREDITO_ENCA e where e.ID_CUENTA_FINAN IN(5,49,50,51) and e.ID_ZAFRA = @ID_ZAFRA and e.CODIPROVEEDOR = @CODIPROVEEDOR and e.ES_SALDO_INSOLUTO = 0) , 0) 
	----set @@_DESEMBOLSOS_EFECTIVOZ2 = isnull(  (select sum(e.SALDO + e.INTERES + e.IVA_INTERES) from CREDITO_ENCA e where e.ID_CUENTA_FINAN IN(5,49,50,51) and e.ID_ZAFRA = @ID_ZAFRA2 and e.CODIPROVEEDOR = @CODIPROVEEDOR and e.ES_SALDO_INSOLUTO = 0) , 0) 
				              
					
	select @@_OIP1 = MONTO, @@_OIP1_BANCO = '(' + NOMBRE_BANCO + ')', @@_OIP1_UID = UID_OPI_CONTRATO
	from 
		(select ROW_NUMBER() OVER(ORDER BY sa.FECHA) as orden, sa.MONTO, b.NOMBRE_BANCO, sa.UID_OPI_CONTRATO from SOLIC_OPI sa, BANCOS b where sa.ID_ESTADO = 2 and sa.CODIBANCO = b.CODIBANCO and sa.ID_ZAFRA = @ID_ZAFRA_INI and sa.CODIPROVEEDOR = @CODIPROVEEDOR) as t -- and (select count(1) from SOLIC_OPI_CONTRATOS sc, @TABLA_CONTRATOS c where sc.ID_OPI = sa.ID_OPI and c.CODICONTRATO = sc.CODICONTRATO) > 0 ) as t
	where orden = 1	
	select @@_OIP1Z2 = MONTO, @@_OIP1_BANCOZ2 = '(' + NOMBRE_BANCO + ')', @@_OIP1_UID = UID_OPI_CONTRATO
	from 
		(select ROW_NUMBER() OVER(ORDER BY sa.FECHA) as orden, sa.MONTO, b.NOMBRE_BANCO, sa.UID_OPI_CONTRATO from SOLIC_OPI sa, BANCOS b where sa.ID_ESTADO = 2 and sa.CODIBANCO = b.CODIBANCO and sa.ID_ZAFRA = @ID_ZAFRA_INI and sa.CODIPROVEEDOR = @CODIPROVEEDOR) as t -- and (select count(1) from SOLIC_OPI_CONTRATOS sc, @TABLA_CONTRATOS c where sc.ID_OPI = sa.ID_OPI and c.CODICONTRATO = sc.CODICONTRATO) > 0 ) as t
	where orden = 1	

	select @@_OIP2 = MONTO, @@_OIP2_BANCOZ2 = '(' + NOMBRE_BANCO + ')', @@_OIP2_UID = UID_OPI_CONTRATO
	from 
		(select ROW_NUMBER() OVER(ORDER BY sa.FECHA) as orden, sa.MONTO, b.NOMBRE_BANCO, sa.UID_OPI_CONTRATO from SOLIC_OPI sa, BANCOS b where sa.ID_ESTADO = 2 and sa.CODIBANCO = b.CODIBANCO and sa.ID_ZAFRA = @ID_ZAFRA_INI and sa.CODIPROVEEDOR = @CODIPROVEEDOR) as t -- and (select count(1) from SOLIC_OPI_CONTRATOS sc, @TABLA_CONTRATOS c where sc.ID_OPI = sa.ID_OPI and c.CODICONTRATO = sc.CODICONTRATO) > 0 ) as t
	where orden = 2 
	select @@_OIP2Z2 = MONTO, @@_OIP2_BANCOZ2 = '(' + NOMBRE_BANCO + ')', @@_OIP2_UIDZ2 = UID_OPI_CONTRATO
	from 
		(select ROW_NUMBER() OVER(ORDER BY sa.FECHA) as orden, sa.MONTO, b.NOMBRE_BANCO, sa.UID_OPI_CONTRATO from SOLIC_OPI sa, BANCOS b where sa.ID_ESTADO = 2 and sa.CODIBANCO = b.CODIBANCO and sa.ID_ZAFRA = @ID_ZAFRA_INI and sa.CODIPROVEEDOR = @CODIPROVEEDOR) as t -- and (select count(1) from SOLIC_OPI_CONTRATOS sc, @TABLA_CONTRATOS c where sc.ID_OPI = sa.ID_OPI and c.CODICONTRATO = sc.CODICONTRATO) > 0 ) as t
	where orden = 2 
	
	if @@_OIP1 is null 
		begin
		set @@_OIP1 = 0
		set @@_OIP1_BANCO = ''
		end
	if @@_OIP1Z2 is null 
		begin
		set @@_OIP1Z2 = 0
		set @@_OIP1_BANCOZ2 = ''
		end
	
	if @@_OIP2 is null 
		begin
		set @@_OIP2 = 0
		set @@_OIP2_BANCO = ''
		end	
	if @@_OIP2Z2 is null 
		begin
		set @@_OIP2Z2 = 0
		set @@_OIP2_BANCOZ2 = ''
		end

	if (select count(1) from CREDITO_ENCA where UID_REFERENCIA = @@_OIP1_UID) > 0 
		set @@_OIP1 = (select SALDO from CREDITO_ENCA where UID_REFERENCIA = @@_OIP1_UID)
	if (select count(1) from CREDITO_ENCA where UID_REFERENCIA = @@_OIP1_UIDZ2) > 0 
		set @@_OIP1Z2 = (select SALDO from CREDITO_ENCA where UID_REFERENCIA = @@_OIP1_UIDZ2)

	if (select count(1) from CREDITO_ENCA where UID_REFERENCIA = @@_OIP2_UID) > 0 
		set @@_OIP2 = (select SALDO from CREDITO_ENCA where UID_REFERENCIA = @@_OIP2_UID)
	if (select count(1) from CREDITO_ENCA where UID_REFERENCIA = @@_OIP2_UIDZ2) > 0 
		set @@_OIP2Z2 = (select SALDO from CREDITO_ENCA where UID_REFERENCIA = @@_OIP2_UIDZ2)
		

	
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '090', 'TOTAL AREA CULTIVADA - ha', null, null, null, null, @USUARIO_CREA, GETDATE(), 0, 0,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)				
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '088', '.            ha - PROPIAS', null, null, null, null, @USUARIO_CREA, GETDATE(), 0, 0,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '089', '.            ha - ARRENDADAS', null, null, null, null, @USUARIO_CREA, GETDATE(), 0, 0,		@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '091', 'TCH', null, null, null, null, @USUARIO_CREA, GETDATE(), 0, 0,  @@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '092', 'TOTAL t', null, null, null, null, @USUARIO_CREA, GETDATE(), 0, 0, @@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)	
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '093', 'kg AZUCAR/t', null, null, null, null, @USUARIO_CREA, GETDATE(), 0, 0,		@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '094', 'TOTAL kg DE AZUCAR', null, null, null, null, @USUARIO_CREA, GETDATE(), 0, 0,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '095', 'V.I.P. VALOR INICIAL DE PAGO - LIBRA AZUCAR', null, null, null, null, @USUARIO_CREA, GETDATE(), 0, 0,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '099', 'A. INGRESOS PROYECTADOS', null, null, null, null, @USUARIO_CREA, GETDATE(), 0, 1,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '000', 'B. MENOS CAT', null, null, null, null, @USUARIO_CREA, GETDATE(), 0, 1,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '001', '.            CORTE TOTAL', null, null, null, null, @USUARIO_CREA, GETDATE(), 0, 0,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '002', '.            ALZA TOTAL', null, null, null, null, @USUARIO_CREA, GETDATE(), 0, 0,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '003', '.            TRANSPORTE TOTAL', null, null, null, null, @USUARIO_CREA, GETDATE(), 0, 0,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '004', '.                             CAT TOTAL', null, null, null, null, @USUARIO_CREA, GETDATE(), 0, 0,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '005', 'C. INGRESOS DESPUES DE CAT', null, null, null, null, @USUARIO_CREA, GETDATE(), 0, 1,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, 'EGR', 'MENOS: EGRESOS PROYECTADOS', null, null, null, null, @USUARIO_CREA, GETDATE(), 0, 1,	null,null,null,null,null,null,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '1', 'SALDOS INSOLUTOS ZAFRA PREVIA', null, null, null, 1, @USUARIO_CREA, GETDATE(), 0, 0,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '4', 'SUMINISTRO FERTILIZANTES', null, null, null, 1, @USUARIO_CREA, GETDATE(), 0, 0,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '5', 'SUMINISTRO HERBICIDAS', null, null, null, 1, @USUARIO_CREA, GETDATE(), 0, 0,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '6', 'SUMINISTRO INSECTICIDAS', null, null, null, 1, @USUARIO_CREA, GETDATE(), 0, 0,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '7', 'SUMINISTRO DE INHIBIDORES', null, null, null, 1, @USUARIO_CREA, GETDATE(), 0, 0,		@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 		
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '8', 'SUMINISTRO DE MADURANTES', null, null, null, 1, @USUARIO_CREA, GETDATE(), 0, 0,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '9', 'SERVICIO DE MAQUINARIA', null, null, null, 1, @USUARIO_CREA, GETDATE(), 0, 0,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '10', 'DESEMBOLSOS EN EFECTIVO', null, null, null, 1, @USUARIO_CREA, GETDATE(), 0, 0,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '11', 'CUOTAS CREDITOS DE LARGO PLAZO', null, null, null, 1, @USUARIO_CREA, GETDATE(), 0, 0,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '12', 'CREDITO DE AVIO', null, null, null, 1, @USUARIO_CREA, GETDATE(), 0, 0,	0,0,0,0,0,0,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '13', 'APLICACION AEREA', null, null, null, 1, @USUARIO_CREA, GETDATE(), 0, 0,	  @@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '14', 'CAÑA SEMILLA', null, null, null, 1, @USUARIO_CREA, GETDATE(), 0, 0,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '15', 'OTRAS CUENTAS', null, null, null, 1, @USUARIO_CREA, GETDATE(), 0, 0,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '16', 'SOLICITUD EN TRAMITE', null, null, null, 1, @USUARIO_CREA, GETDATE(), 0, 0,  @@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '17', 'O.I.P. ', null, null, null, 1, @USUARIO_CREA, GETDATE(), 0, 0,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)
	set @@ORDEN = dbo.fID_PRE_ANALISIS_DETA(@ID_ENCA)
	--set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	--set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	--set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	--set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	--set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	--set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	--insert into PRE_ANALISIS_DETA 
	--values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '18', 'O.I.P. ' + @@_OIP2_BANCO, null, null, null, 1, @USUARIO_CREA, GETDATE(), 0, 0,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)	
		
	
	-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%   AJUSTE DEL CAT POR LAS ENTREGAS REALIZADAS ANTES DEL CORTE  %%%%%%%%%%%%%%%%%%%%%%%%%%
	set @@PROVI_REAL_TC = (
				ISNULL(
					(
					SELECT SUM(B.NETOTONEL) 
					FROM ENVIO E, LOTES L, CONTRATO C, BASCULA B 
					WHERE E.ID_ENVIO = B.ID_ENVIO 
					AND E.ACCESLOTE = L.ACCESLOTE
					AND L.CODICONTRATO = C.CODICONTRATO
					AND C.CODIPROVEEDOR = @CODIPROVEEDOR 
					AND (SELECT COUNT(1) FROM ZAFRA Z WHERE Z.ID_ZAFRA = E.ID_ZAFRA AND Z.ACTIVA = 1) > 0
					AND NOT B.NETOTONEL IS NULL 					
					AND E.CATORCENA = (SELECT Z.CATORCENA FROM ZAFRA Z WHERE Z.ID_ZAFRA = E.ID_ZAFRA)
					)
					, 0)	)

	insert  #DETA
	SELECT E.ID_ZAFRA, 33 AS ORDEN, ROUND(
							ROUND( SUM(B.NETOTONEL) * @@REND_HISTO , 2) * Z.PRECIO_LIBRA_AZUCAR 
						, 2) 
					   - ROUND( SUM(B.NETOTONEL) * (Z.TARIFA_ROZA_MODFINAN + ROUND(Z.TARIFA_ROZA_MODFINAN * @TASA_IVA ,2)) , 2) 
					   - ROUND( SUM(B.NETOTONEL) * (Z.TARIFA_ALZA_MODFINAN + ROUND(Z.TARIFA_ALZA_MODFINAN * @TASA_IVA ,2)) , 2) 
					   - ROUND( SUM(B.NETOTONEL) * @TARIFA_FLETE , 2)
	FROM ENVIO E, LOTES L, CONTRATO C, BASCULA B, ZAFRA Z
	WHERE E.ID_ENVIO = B.ID_ENVIO 
	AND E.ACCESLOTE = L.ACCESLOTE
	AND L.CODICONTRATO = C.CODICONTRATO
	AND C.CODIPROVEEDOR = @CODIPROVEEDOR 
	AND E.ID_ZAFRA = Z.ID_ZAFRA
	AND Z.ACTIVA = 1
	AND NOT B.NETOTONEL IS NULL 					
	AND E.CATORCENA = (SELECT Z.CATORCENA FROM ZAFRA Z WHERE Z.ID_ZAFRA = E.ID_ZAFRA)
	GROUP BY E.ID_ZAFRA, Z.PRECIO_LIBRA_AZUCAR, Z.TARIFA_ROZA_MODFINAN, Z.TARIFA_ALZA_MODFINAN
			
	set @@ORDEN = 33
	set @@MONTO1 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI and ORDEN = @@ORDEN)
	set @@MONTO2 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+1 and ORDEN = @@ORDEN)
	set @@MONTO3 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+2 and ORDEN = @@ORDEN)
	set @@MONTO4 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+3 and ORDEN = @@ORDEN)
	set @@MONTO5 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+4 and ORDEN = @@ORDEN)
	set @@MONTO6 = (select isnull(sum(VALOR),0) from #DETA where ID_ZAFRA = @ID_ZAFRA_INI+5 and ORDEN = @@ORDEN)
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '99', 'MENOS: REGISTRO PROVISIONAL DE ABONOS EN TIEMPO REAL', null, null, null, 2, @USUARIO_CREA, GETDATE(), 0, 1,		@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)		
	-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

	set @@ORDEN = 34
	set @@MONTO1 = cast(  (select isnull(sum(MONTO1),0) from PRE_ANALISIS_DETA WHERE ID_CATE_REF = 1 AND UID_REF = @UID_REF) - (select isnull(sum(MONTO1),0) from PRE_ANALISIS_DETA WHERE ID_CATE_REF = 2 AND UID_REF = @UID_REF) as numeric(20,2))
	set @@MONTO2 = cast(  (select isnull(sum(MONTO2),0) from PRE_ANALISIS_DETA WHERE ID_CATE_REF = 1 AND UID_REF = @UID_REF) - (select isnull(sum(MONTO2),0) from PRE_ANALISIS_DETA WHERE ID_CATE_REF = 2 AND UID_REF = @UID_REF) as numeric(20,2))
	set @@MONTO3 = cast(  (select isnull(sum(MONTO3),0) from PRE_ANALISIS_DETA WHERE ID_CATE_REF = 1 AND UID_REF = @UID_REF) - (select isnull(sum(MONTO3),0) from PRE_ANALISIS_DETA WHERE ID_CATE_REF = 2 AND UID_REF = @UID_REF) as numeric(20,2))
	set @@MONTO4 = cast(  (select isnull(sum(MONTO4),0) from PRE_ANALISIS_DETA WHERE ID_CATE_REF = 1 AND UID_REF = @UID_REF) - (select isnull(sum(MONTO4),0) from PRE_ANALISIS_DETA WHERE ID_CATE_REF = 2 AND UID_REF = @UID_REF) as numeric(20,2))
	set @@MONTO5 = cast(  (select isnull(sum(MONTO5),0) from PRE_ANALISIS_DETA WHERE ID_CATE_REF = 1 AND UID_REF = @UID_REF) - (select isnull(sum(MONTO5),0) from PRE_ANALISIS_DETA WHERE ID_CATE_REF = 2 AND UID_REF = @UID_REF) as numeric(20,2))
	set @@MONTO6 = cast(  (select isnull(sum(MONTO6),0) from PRE_ANALISIS_DETA WHERE ID_CATE_REF = 1 AND UID_REF = @UID_REF) - (select isnull(sum(MONTO6),0) from PRE_ANALISIS_DETA WHERE ID_CATE_REF = 2 AND UID_REF = @UID_REF) as numeric(20,2))
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '006', 'D. TOTAL EGRESOS PROYECTADOS', null, null, 1, null, @USUARIO_CREA, GETDATE(), 0, 1,	@@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)

	set @@ORDEN = 35
	set @@MONTO1 = (select isnull(sum(MONTO1),0) from PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '005') - (select isnull(sum(MONTO1),0) from PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '006')
	set @@MONTO2 = (select isnull(sum(MONTO2),0) from PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '005') - (select isnull(sum(MONTO2),0) from PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '006')
	set @@MONTO3 = (select isnull(sum(MONTO3),0) from PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '005') - (select isnull(sum(MONTO3),0) from PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '006')
	set @@MONTO4 = (select isnull(sum(MONTO4),0) from PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '005') - (select isnull(sum(MONTO4),0) from PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '006')
	set @@MONTO5 = (select isnull(sum(MONTO5),0) from PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '005') - (select isnull(sum(MONTO5),0) from PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '006')
	set @@MONTO6 = (select isnull(sum(MONTO6),0) from PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '005') - (select isnull(sum(MONTO6),0) from PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '006')
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '007', 'E. RESULTADO PROYECTADO (C-D)', null, null, 1, null, @USUARIO_CREA, GETDATE(), 0, 1, @@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)

	set @@ORDEN = 36
	set @@MONTO1 = dbo.fDividir2Dec( (SELECT isnull(SUM(MONTO1),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '007') , (SELECT isnull(SUM(MONTO1),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '090') )
	set @@MONTO2 = dbo.fDividir2Dec( (SELECT isnull(SUM(MONTO2),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '007') , (SELECT isnull(SUM(MONTO2),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '090') )
	set @@MONTO3 = dbo.fDividir2Dec( (SELECT isnull(SUM(MONTO3),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '007') , (SELECT isnull(SUM(MONTO3),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '090') )
	set @@MONTO4 = dbo.fDividir2Dec( (SELECT isnull(SUM(MONTO4),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '007') , (SELECT isnull(SUM(MONTO4),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '090') )
	set @@MONTO5 = dbo.fDividir2Dec( (SELECT isnull(SUM(MONTO5),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '007') , (SELECT isnull(SUM(MONTO5),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '090') )
	set @@MONTO6 = dbo.fDividir2Dec( (SELECT isnull(SUM(MONTO6),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '007') , (SELECT isnull(SUM(MONTO6),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '090') )
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '011', '.            RESULTADO - ha', null, null, null, null, @USUARIO_CREA, GETDATE(), 0, 0, @@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6,0)

	set @@ORDEN = 37
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '009', 'MONTO CREDITO SOLICITADO', null, null, 1, null, @USUARIO_CREA, GETDATE(), 1, 1, @MONTO_SOLICITADO, @MONTO_SOLICITADO2, 0, 0, 0, 0, 0)

	set @@ORDEN = 38
	set @@MONTO1 = (SELECT SUM(MONTO1) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '007') - @MONTO_SOLICITADO
	set @@MONTO2 = (SELECT SUM(MONTO2) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '007') - @MONTO_SOLICITADO2
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '008', 'F. RESULTADO FINAL PROYECTADO', null, null, 1, null, @USUARIO_CREA, GETDATE(), 0, 0, @@MONTO1, @@MONTO2, 0, 0, 0, 0, 0)

	set @@ORDEN = 39
	set @@MONTO1 = dbo.fDividir2Dec( (SELECT SUM(MONTO1) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '008') , (SELECT isnull(SUM(MONTO1),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '090') )
	set @@MONTO2 = dbo.fDividir2Dec( (SELECT SUM(MONTO2) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '008') , (SELECT isnull(SUM(MONTO2),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '090') )
	insert into PRE_ANALISIS_DETA 
	values((SELECT ISNULL(MAX(ID_DETA),0) + 1 FROM PRE_ANALISIS_DETA), @ID_ENCA, @UID_REF, @@ORDEN, '010', '.            RESULTADO FINAL - ha',  null, null, null, null, @USUARIO_CREA, GETDATE(), 0, 0,@@MONTO1, @@MONTO2, 0, 0, 0, 0, 0)

	/*  ESTABLECIENDO TOTALES */
	UPDATE PRE_ANALISIS_DETA SET TOTAL = NULL WHERE ID_ENCA = @ID_ENCA
	UPDATE PRE_ANALISIS_DETA SET TOTAL = MONTO1 + MONTO2 + MONTO3 + MONTO4 + MONTO5 + MONTO6 WHERE ID_ENCA = @ID_ENCA AND NUMERO NOT IN('093','095')
	

	/*  ANALISIS DE TONELADAS */
	SET @@MONTO1 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO1,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '099' ) , (SELECT isnull(SUM(MONTO1),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO2 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO2,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '099' ) , (SELECT isnull(SUM(MONTO2),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO3 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO3,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '099' ) , (SELECT isnull(SUM(MONTO3),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO4 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO4,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '099' ) , (SELECT isnull(SUM(MONTO4),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO5 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO5,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '099' ) , (SELECT isnull(SUM(MONTO5),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO6 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO6,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '099' ) , (SELECT isnull(SUM(MONTO6),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	INSERT INTO PRE_ANALISIS_TC VALUES((SELECT ISNULL(MAX(ID_ANATC),0) + 1 FROM PRE_ANALISIS_TC), @ID_ENCA, 1, 'INGRESO VIP', @ID_ZAFRA_INI, @ID_ZAFRA_INI+1, @ID_ZAFRA_INI+2, @ID_ZAFRA_INI+3, @ID_ZAFRA_INI+4, @ID_ZAFRA_INI+5, @@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6 )

	SET @@MONTO1 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO1,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '000' ) , (SELECT isnull(SUM(MONTO1),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO2 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO2,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '000' ) , (SELECT isnull(SUM(MONTO2),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO3 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO3,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '000' ) , (SELECT isnull(SUM(MONTO3),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO4 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO4,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '000' ) , (SELECT isnull(SUM(MONTO4),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO5 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO5,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '000' ) , (SELECT isnull(SUM(MONTO5),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO6 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO6,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '000' ) , (SELECT isnull(SUM(MONTO6),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	INSERT INTO PRE_ANALISIS_TC VALUES((SELECT ISNULL(MAX(ID_ANATC),0) + 1 FROM PRE_ANALISIS_TC), @ID_ENCA, 2, 'CAT', @ID_ZAFRA_INI, @ID_ZAFRA_INI+1, @ID_ZAFRA_INI+2, @ID_ZAFRA_INI+3, @ID_ZAFRA_INI+4, @ID_ZAFRA_INI+5, @@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6 )
	
	SET @@MONTO1 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO1,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '005' ) , (SELECT isnull(SUM(MONTO1),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO2 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO2,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '005' ) , (SELECT isnull(SUM(MONTO2),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO3 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO3,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '005' ) , (SELECT isnull(SUM(MONTO3),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO4 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO4,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '005' ) , (SELECT isnull(SUM(MONTO4),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO5 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO5,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '005' ) , (SELECT isnull(SUM(MONTO5),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO6 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO6,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '005' ) , (SELECT isnull(SUM(MONTO6),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	INSERT INTO PRE_ANALISIS_TC VALUES((SELECT ISNULL(MAX(ID_ANATC),0) + 1 FROM PRE_ANALISIS_TC), @ID_ENCA, 3, 'NETO DESP CAT', @ID_ZAFRA_INI, @ID_ZAFRA_INI+1, @ID_ZAFRA_INI+2, @ID_ZAFRA_INI+3, @ID_ZAFRA_INI+4, @ID_ZAFRA_INI+5, @@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6 )	

	SET @@MONTO1 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO1,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '006' ) , (SELECT isnull(SUM(MONTO1),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO2 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO2,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '006' ) , (SELECT isnull(SUM(MONTO2),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO3 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO3,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '006' ) , (SELECT isnull(SUM(MONTO3),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO4 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO4,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '006' ) , (SELECT isnull(SUM(MONTO4),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO5 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO5,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '006' ) , (SELECT isnull(SUM(MONTO5),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO6 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO6,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '006' ) , (SELECT isnull(SUM(MONTO6),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	INSERT INTO PRE_ANALISIS_TC VALUES((SELECT ISNULL(MAX(ID_ANATC),0) + 1 FROM PRE_ANALISIS_TC), @ID_ENCA, 4, 'EGRESOS', @ID_ZAFRA_INI, @ID_ZAFRA_INI+1, @ID_ZAFRA_INI+2, @ID_ZAFRA_INI+3, @ID_ZAFRA_INI+4, @ID_ZAFRA_INI+5, @@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6 )	

	SET @@MONTO1 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO1,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '007' ) , (SELECT isnull(SUM(MONTO1),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO2 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO2,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '007' ) , (SELECT isnull(SUM(MONTO2),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO3 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO3,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '007' ) , (SELECT isnull(SUM(MONTO3),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO4 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO4,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '007' ) , (SELECT isnull(SUM(MONTO4),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO5 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO5,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '007' ) , (SELECT isnull(SUM(MONTO5),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	SET @@MONTO6 = dbo.fDividir2Dec( (SELECT ISNULL(MONTO6,0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '007' ) , (SELECT isnull(SUM(MONTO6),0) FROM PRE_ANALISIS_DETA WHERE UID_REF = @UID_REF AND NUMERO = '092') )
	INSERT INTO PRE_ANALISIS_TC VALUES((SELECT ISNULL(MAX(ID_ANATC),0) + 1 FROM PRE_ANALISIS_TC), @ID_ENCA, 5, 'RESULT PROYECT', @ID_ZAFRA_INI, @ID_ZAFRA_INI+1, @ID_ZAFRA_INI+2, @ID_ZAFRA_INI+3, @ID_ZAFRA_INI+4, @ID_ZAFRA_INI+5, @@MONTO1,@@MONTO2,@@MONTO3,@@MONTO4,@@MONTO5,@@MONTO6 )	
	
		
	/*  HISTORIAL DE ZAFRAS */
	DECLARE @@ID_ZAFRA INT,
			@@MZ NUMERIC(20,2),
			@@TC NUMERIC(20,2),
			@@TC_MZ NUMERIC(20,2),
			@@LBS NUMERIC(20,2),
			@@LBS_TC NUMERIC(20,2),
			@@FTO NUMERIC(20,2)			
										
	SET @@ID_ZAFRA = @ID_ZAFRA_INI
	SET @@MZ = ISNULL( (SELECT SUM(LC.MZ_CENSO) FROM LOTES_COSECHA LC, LOTES L, CONTRATO C WHERE C.CODICONTRATO = L.CODICONTRATO AND C.CODIPROVEEDOR = @CODIPROVEEDOR AND LC.ACCESLOTE = L.ACCESLOTE AND LC.ID_ZAFRA = @@ID_ZAFRA) , 0)
	SET @@TC = ISNULL( (SELECT SUM(LC.TONEL_CENSO) FROM LOTES_COSECHA LC, LOTES L, CONTRATO C WHERE C.CODICONTRATO = L.CODICONTRATO AND C.CODIPROVEEDOR = @CODIPROVEEDOR AND LC.ACCESLOTE = L.ACCESLOTE AND LC.ID_ZAFRA = @@ID_ZAFRA) , 0)
	SET @@TC_MZ = dbo.fDividir2Dec(@@TC,@@MZ)
	SET @@LBS_TC = @@REND_HISTO
	SET @@LBS = ISNULL( (SELECT SUM(LC.TONEL_CENSO) FROM LOTES_COSECHA LC, LOTES L, CONTRATO C WHERE C.CODICONTRATO = L.CODICONTRATO AND C.CODIPROVEEDOR = @CODIPROVEEDOR AND LC.ACCESLOTE = L.ACCESLOTE AND LC.ID_ZAFRA = @@ID_ZAFRA) , 0) * @@LBS_TC	
	SET @@FTO = ISNULL( (SELECT SUM(E.CARGO) FROM CREDITO_ENCA E WHERE E.ID_CUENTA_FINAN <> 1 AND E.ID_ZAFRA = @@ID_ZAFRA), 0)
	INSERT INTO PRE_ANALISIS_ZAFRA VALUES( (SELECT ISNULL(MAX(ID_ANAZAFRA),0) + 1 FROM PRE_ANALISIS_ZAFRA), @ID_ENCA, 1, 'TOTAL ha', NULL,NULL,NULL,@@ID_ZAFRA,NULL,NULL,NULL,@@MZ)
	INSERT INTO PRE_ANALISIS_ZAFRA VALUES( (SELECT ISNULL(MAX(ID_ANAZAFRA),0) + 1 FROM PRE_ANALISIS_ZAFRA), @ID_ENCA, 2, 'TOTAL t', NULL,NULL,NULL,@@ID_ZAFRA,NULL,NULL,NULL,@@TC)
	INSERT INTO PRE_ANALISIS_ZAFRA VALUES( (SELECT ISNULL(MAX(ID_ANAZAFRA),0) + 1 FROM PRE_ANALISIS_ZAFRA), @ID_ENCA, 3, 'TCH', NULL,NULL,NULL,@@ID_ZAFRA,NULL,NULL,NULL,@@TC_MZ)
	INSERT INTO PRE_ANALISIS_ZAFRA VALUES( (SELECT ISNULL(MAX(ID_ANAZAFRA),0) + 1 FROM PRE_ANALISIS_ZAFRA), @ID_ENCA, 4, 'kg /t', NULL,NULL,NULL,@@ID_ZAFRA,NULL,NULL,NULL,@@LBS_TC)
	
	SET @@ID_ZAFRA = @ID_ZAFRA_INI - 1
	SET @@MZ = ISNULL( (SELECT SUM(LC.MZ_ENTREGADA) FROM LOTES_COSECHA LC, LOTES L, CONTRATO C WHERE C.CODICONTRATO = L.CODICONTRATO AND C.CODIPROVEEDOR = @CODIPROVEEDOR AND LC.ACCESLOTE = L.ACCESLOTE AND LC.ID_ZAFRA = @@ID_ZAFRA) , 0)
	SET @@TC = ISNULL( (SELECT SUM(M.NETOTONEL) FROM MOV_CATORCENA M WHERE M.CODIPROVEE = @@CODIPROVEE AND M.ID_ZAFRA = @@ID_ZAFRA) , 0)
	SET @@TC_MZ = dbo.fDividir2Dec(@@TC,@@MZ)
	SET @@LBS = ISNULL( (SELECT SUM(M.AZUCAR_CATORCENA_REAL) FROM MOV_CATORCENA M WHERE M.CODIPROVEE = @@CODIPROVEE AND M.ID_ZAFRA = @@ID_ZAFRA) , 0)
	SET @@LBS_TC = dbo.fDividir2Dec(@@LBS,@@TC)
	SET @@FTO = ISNULL( (SELECT SUM(E.CARGO) FROM CREDITO_ENCA E WHERE E.ID_CUENTA_FINAN <> 1 AND E.ID_ZAFRA = @@ID_ZAFRA), 0)
	UPDATE Z SET ID_ZAFRA3 = @@ID_ZAFRA, VALOR_Z3 = @@MZ FROM PRE_ANALISIS_ZAFRA Z WHERE ID_ENCA = @ID_ENCA AND ORDEN = 1
	UPDATE Z SET ID_ZAFRA3 = @@ID_ZAFRA, VALOR_Z3 = @@TC FROM PRE_ANALISIS_ZAFRA Z WHERE ID_ENCA = @ID_ENCA AND ORDEN = 2
	UPDATE Z SET ID_ZAFRA3 = @@ID_ZAFRA, VALOR_Z3 = @@TC_MZ FROM PRE_ANALISIS_ZAFRA Z WHERE ID_ENCA = @ID_ENCA AND ORDEN = 3
	UPDATE Z SET ID_ZAFRA3 = @@ID_ZAFRA, VALOR_Z3 = @@LBS_TC FROM PRE_ANALISIS_ZAFRA Z WHERE ID_ENCA = @ID_ENCA AND ORDEN = 4
	
	SET @@ID_ZAFRA = @ID_ZAFRA_INI - 2
	SET @@MZ = ISNULL( (SELECT SUM(LC.MZ_ENTREGADA) FROM LOTES_COSECHA LC, LOTES L, CONTRATO C WHERE C.CODICONTRATO = L.CODICONTRATO AND C.CODIPROVEEDOR = @CODIPROVEEDOR AND LC.ACCESLOTE = L.ACCESLOTE AND LC.ID_ZAFRA = @@ID_ZAFRA) , 0)
	SET @@TC = ISNULL( (SELECT SUM(M.NETOTONEL) FROM MOV_CATORCENA M WHERE M.CODIPROVEE = @@CODIPROVEE AND M.ID_ZAFRA = @@ID_ZAFRA) , 0)
	SET @@TC_MZ = dbo.fDividir2Dec(@@TC,@@MZ)
	SET @@LBS = ISNULL( (SELECT SUM(M.AZUCAR_CATORCENA_REAL) FROM MOV_CATORCENA M WHERE M.CODIPROVEE = @@CODIPROVEE AND M.ID_ZAFRA = @@ID_ZAFRA) , 0)
	SET @@LBS_TC = dbo.fDividir2Dec(@@LBS,@@TC)
	SET @@FTO = ISNULL( (SELECT SUM(E.CARGO) FROM CREDITO_ENCA E WHERE E.ID_CUENTA_FINAN <> 1 AND E.ID_ZAFRA = @@ID_ZAFRA), 0)
	UPDATE Z SET ID_ZAFRA2 = @@ID_ZAFRA, VALOR_Z2 = @@MZ FROM PRE_ANALISIS_ZAFRA Z WHERE ID_ENCA = @ID_ENCA AND ORDEN = 1
	UPDATE Z SET ID_ZAFRA2 = @@ID_ZAFRA, VALOR_Z2 = @@TC FROM PRE_ANALISIS_ZAFRA Z WHERE ID_ENCA = @ID_ENCA AND ORDEN = 2
	UPDATE Z SET ID_ZAFRA2 = @@ID_ZAFRA, VALOR_Z2 = @@TC_MZ FROM PRE_ANALISIS_ZAFRA Z WHERE ID_ENCA = @ID_ENCA AND ORDEN = 3
	UPDATE Z SET ID_ZAFRA2 = @@ID_ZAFRA, VALOR_Z2 = @@LBS_TC FROM PRE_ANALISIS_ZAFRA Z WHERE ID_ENCA = @ID_ENCA AND ORDEN = 4	

	SET @@ID_ZAFRA = @ID_ZAFRA_INI - 3
	SET @@MZ = ISNULL( (SELECT SUM(LC.MZ_ENTREGADA) FROM LOTES_COSECHA LC, LOTES L, CONTRATO C WHERE C.CODICONTRATO = L.CODICONTRATO AND C.CODIPROVEEDOR = @CODIPROVEEDOR AND LC.ACCESLOTE = L.ACCESLOTE AND LC.ID_ZAFRA = @@ID_ZAFRA) , 0)
	SET @@TC = ISNULL( (SELECT SUM(M.NETOTONEL) FROM MOV_CATORCENA M WHERE M.CODIPROVEE = @@CODIPROVEE AND M.ID_ZAFRA = @@ID_ZAFRA) , 0)
	SET @@TC_MZ = dbo.fDividir2Dec(@@TC,@@MZ)
	SET @@LBS = ISNULL( (SELECT SUM(M.AZUCAR_CATORCENA_REAL) FROM MOV_CATORCENA M WHERE M.CODIPROVEE = @@CODIPROVEE AND M.ID_ZAFRA = @@ID_ZAFRA) , 0)
	SET @@LBS_TC = dbo.fDividir2Dec(@@LBS,@@TC)
	SET @@FTO = ISNULL( (SELECT SUM(E.CARGO) FROM CREDITO_ENCA E WHERE E.ID_CUENTA_FINAN <> 1 AND E.ID_ZAFRA = @@ID_ZAFRA), 0)
	UPDATE Z SET ID_ZAFRA1 = @@ID_ZAFRA, VALOR_Z1 = @@MZ FROM PRE_ANALISIS_ZAFRA Z WHERE ID_ENCA = @ID_ENCA AND ORDEN = 1
	UPDATE Z SET ID_ZAFRA1 = @@ID_ZAFRA, VALOR_Z1 = @@TC FROM PRE_ANALISIS_ZAFRA Z WHERE ID_ENCA = @ID_ENCA AND ORDEN = 2
	UPDATE Z SET ID_ZAFRA1 = @@ID_ZAFRA, VALOR_Z1 = @@TC_MZ FROM PRE_ANALISIS_ZAFRA Z WHERE ID_ENCA = @ID_ENCA AND ORDEN = 3
	UPDATE Z SET ID_ZAFRA1 = @@ID_ZAFRA, VALOR_Z1 = @@LBS_TC FROM PRE_ANALISIS_ZAFRA Z WHERE ID_ENCA = @ID_ENCA AND ORDEN = 4
	
	DROP TABLE #Z_COSECHA
	DROP TABLE #DETA
	DROP TABLE #Z_RENDS

	--SELECT      * 	FROM            PRE_ANALISIS_DETA WHERE USUARIO_CREA = 'admin'


END



